{{- if ne .Values.postgres.password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-postgres
  namespace: gitlab
type: kubernetes.io/opaque
stringData:
  password: {{ .Values.postgres.password }}
{{- end }}
