apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
spec:
  network:
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Ingress
        podLabels:
          app: webservice
        port: 8181
        description: "Runner Ingress Workhorse"

      - direction: Ingress
        podLabels:
          app: webservice
        remoteNamespace: istio-tenant-gateway
        remotePodLabels:
          app: tenant-ingressgateway
          istio: tenant-ingressgateway
        port: 8181
        description: "Istio Tenant Ingressgateway Webservice"

      - direction: Ingress
        podLabels:
          app: sidekiq
        remoteNamespace: istio-tenant-gateway
        remotePodLabels:
          app: tenant-ingressgateway
          istio: tenant-ingressgateway
        port: 8080
        description: "Istio Tenant Ingressgateway Sidekiq"

      - direction: Ingress
        podLabels:
          app: registry
        remoteNamespace: istio-tenant-gateway
        remotePodLabels:
          app: tenant-ingressgateway
          istio: tenant-ingressgateway
        port: 5000
        description: "Istio Tenant Ingressgateway Registry"

      - direction: Ingress
        remoteNamespace: monitoring
        remotePodLabels:
          app: prometheus
        podLabels:
          app: gitlab-exporter
        port: 9168
        description: "Monitoring Exporter"

      - direction: Ingress
        podLabels:
          app: runner
        remoteNamespace: monitoring
        remotePodLabels:
          app: prometheus

        port: 9252
        description: "Monitoring Runner"

      - direction: Egress
        podLabels:
          app: registry
        remoteGenerated: Anywhere
        description: "Registry Storage"

      - direction: Egress
        podLabels:
          app: sidekiq
        remoteGenerated: Anywhere
        description: "Sidekiq Storage"

      - direction: Egress
        podLabels:
          app: migrations
        remoteGenerated: Anywhere
        description: "Migrations Storage"

      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Egress
        # todo: this is over permissive, need to scope it down
        remoteGenerated: KubeAPI

      - direction: Egress
        remoteNamespace: tempo
        remotePodLabels:
          app.kubernetes.io/name: tempo
        port: 9411
        description: "Tempo"

      - direction: Egress
        podLabels:
          app: webservice
        port: 443
        description: "SSO"

      - direction: Egress
        podLabels:
          app: webservice
        remoteGenerated: Anywhere
        description: "Webservice Storage"
