---
tasks:
  - name: install
    description: Check if Grype is installed, if not install it
    actions:
      - cmd: |
          if ! command -v grype &> /dev/null; then
            echo "Grype could not be found, installing..."
            curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          else
            echo "Grype is already installed."
          fi

  - name: create-grype-config
    description: Generate a .grype.yaml configuration file with registry credentials
    actions:
      - cmd: |
          bash -c '
            # Ensure the environment variables are set
            if [[ -z "$GRYPE_USERNAME" || -z "$GRYPE_PASSWORD" ]]; then
              echo "GRYPE_USERNAME and GRYPE_PASSWORD environment variables must be set."
              exit 1
            fi

            # Create or overwrite the .grype.yaml file
            cat > .grype.yaml << EOF
            # Grype Configuration File
            registry:
              auth:
                - authority: "registry1.dso.mil"
                  username: "$GRYPE_USERNAME"
                  password: "$GRYPE_PASSWORD"
            EOF

            echo ".grype.yaml configuration file created with registry credentials."
          '
