tasks:
  - name: fix
    description: "Fix formatting issues in the repo"
    actions:
      - description: "Pepr Format"
        cmd: npx pepr format

  - name: check
    description: "Run linting checks"
    actions:
      - description: install yamllint deps
        cmd: pip install yamllint
      - description: yaml lint
        cmd: yamllint . -c .yamllint --no-warnings
