includes:
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common-tasks/v0.2.2/tasks/create.yaml
  - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common-tasks/v0.2.2/tasks/publish.yaml

variables:
  - name: TARGET_REPO
    default: oci://ghcr.io/defenseunicorns/packages/uds

  - name: VERSION
    description: The version of the package to build
    # x-release-please-start-version
    default: "16.9.2-uds.0"
    # x-release-please-end

  - name: FLAVOR
    default: "registry1"

tasks:
  - name: package
    description: Build and publish the packages
    actions:
      - description: Create the AMD64 package
        task: create:package
        with:
          options: -a amd64

      - description: Create the ARM64 package
        task: create:package
        with:
          options: -a arm64

      - description: Publish the packages
        task: publish:package
