---
tasks:
  - name: grype-scan-sbom
    description: Create a UDS package with configurable flavor and extract the SBOM from all created packages and analyze for vulnerabilities
    actions:
      - cmd: |
          for flavor in upstream registry1; do
            uds zarf package create . --flavor="$flavor" --confirm --no-progress -o sbom
            for file in sbom/*.zst; do
              uds zarf package inspect "$file" --sbom-out ./sbom --no-progress
            done
          done
          if ! command -v grype &> /dev/null; then
            echo "Grype could not be found, installing..."
            curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          fi
          mkdir -p ./sarif
          find ./sbom -type f -name '*.json' -exec sh -c '
            for sbom_file; do
              base=$(basename "${sbom_file}" .json)
              grype sbom:"${sbom_file}" -o sarif > "./sarif/${base}.sarif"
              echo "Output saved to ./sarif/${base}.sarif"
            done
          ' sh {} +
          echo "All SBOM files processed and analyzed for vulnerabilities."
