---
tasks:
  - name: upstream
    description: Create a UDS package with upstream flavor, extract the SBOM, and analyze for vulnerabilities
    actions:
      - cmd: |
          bash -c '
            flavor="upstream"
            output_dir="sbom/$flavor"
            mkdir -p "$output_dir"
            uds zarf package create . --flavor="$flavor" --confirm --no-progress -o "$output_dir"
            for file in "$output_dir"/*.zst; do
              uds zarf package inspect "$file" --sbom-out "$output_dir" --no-progress
            done
            sarif_output_dir="./sarif"
            mkdir -p "$sarif_output_dir"
            find "sbom/$flavor" -type f -name "*.json" | while read -r json_file; do
              sarif_file_name="${flavor}_$(basename "${json_file}").sarif"
              echo "Processing $json_file"
              echo "Outputting to $sarif_output_dir/$sarif_file_name"
              grype sbom:"$json_file" -o sarif --file "$sarif_output_dir/$sarif_file_name"
              echo "Grype analysis for $json_file exported to $sarif_output_dir/$sarif_file_name (errors ignored)"
              # Extract the base name of the SBOM file without the .json extension
              sbom_base_name=$(basename "$json_file" .json)
              yq eval "(.runs[].results[].locations[].physicalLocation.artifactLocation.uri) = \"$sbom_base_name\"" "$sarif_output_dir/$sarif_file_name" -i
              echo "Updated SARIF file path to $sbom_base_name using yq for $sarif_file_name"
            done
          '

  - name: registry1
    description: Create a UDS package with registry1 flavor, extract the SBOM, and analyze for vulnerabilities
    actions:
      - cmd: |
          bash -c '
            flavor="registry1"
            output_dir="sbom/$flavor"
            mkdir -p "$output_dir"
            uds zarf package create . --flavor="$flavor" --confirm --no-progress -o "$output_dir"
            for file in "$output_dir"/*.zst; do
              uds zarf package inspect "$file" --sbom-out "$output_dir" --no-progress
            done
            sarif_output_dir="./sarif"
            mkdir -p "$sarif_output_dir"
            find "sbom/$flavor" -type f -name "*.json" | while read -r json_file; do
              sarif_file_name="${flavor}_$(basename "${json_file}").sarif"
              echo "Processing $json_file"
              echo "Outputting to $sarif_output_dir/$sarif_file_name"
              grype sbom:"$json_file" -o sarif --file "$sarif_output_dir/$sarif_file_name"
              echo "Grype analysis for $json_file exported to $sarif_output_dir/$sarif_file_name (errors ignored)"
            done
          '
  - name: create-grype-config
    description: Generate a .grype.yaml configuration file with registry credentials
    actions:
      - cmd: |
          bash -c '
            # Ensure the environment variables are set
            if [[ -z "$GRYPE_USERNAME" || -z "$GRYPE_PASSWORD" ]]; then
              echo "GRYPE_USERNAME and GRYPE_PASSWORD environment variables must be set."
              exit 1
            fi

            # Create or overwrite the .grype.yaml file
            cat > .grype.yaml << EOF
            # Grype Configuration File
            registry:
              auth:
                - authority: "registry1.dso.mil"
                  username: "$GRYPE_USERNAME"
                  password: "$GRYPE_PASSWORD"
            EOF

            echo ".grype.yaml configuration file created with registry credentials."
          '
