tasks:
  - name: health-check
    actions:
      - description: GitLab Exporter Health Check
        wait:
          cluster:
            kind: Deployment
            name: gitlab-gitlab-exporter
            namespace: gitlab
            condition: Available

      - description: GitLab Registry Health Check
        wait:
          cluster:
            kind: Deployment
            name: gitlab-registry
            namespace: gitlab
            condition: Available

      - description: GitLab Shell Health Check
        wait:
          cluster:
            kind: Deployment
            name: gitlab-gitlab-shell
            namespace: gitlab
            condition: Available

      - description: GitLab Toolbox Health Check
        wait:
          cluster:
            kind: Deployment
            name: gitlab-toolbox
            namespace: gitlab
            condition: Available

      - description: GitLab Sidekiq Health Check
        wait:
          cluster:
            kind: Deployment
            name: gitlab-sidekiq-all-in-1-v2
            namespace: gitlab
            condition: Available

      - description: GitLab Webservice Health Check
        wait:
          cluster:
            kind: Deployment
            name: gitlab-webservice-default
            namespace: gitlab
            condition: Available

      - description: GitLab Pages Health Check
        wait:
          cluster:
            kind: Deployment
            name: gitlab-gitlab-pages
            namespace: gitlab
            condition: Available

      # StatefulSets don't show conditions themselves so we look for an underlying Pod
      - description: GitLab Gitaly Health Check
        wait:
          cluster:
            kind: Pod
            name: app=gitaly
            namespace: gitlab
            condition: Ready

      - description: GitLab Migrations Health Check
        wait:
          cluster:
            kind: Job
            name: app=migrations
            namespace: gitlab
            condition: Complete

  - name: ingress
    actions:
      - description: GitLab UI Health Check
        wait:
          network:
            protocol: https
            address: gitlab.uds.dev
            code: 200

  - name: ui
    description: GitLab UI Checks
    actions:
      - cmd: npm ci
        dir: tests
      - cmd: npx playwright install --with-deps
        dir: tests
      - cmd: npx playwright test
        dir: tests

  - name: create-doug-admin
    description: Promote Doug to admin (requires running setup:create-doug-user and logging into gitlab ui first)
    actions:
      - cmd: |
          ./uds zarf tools kubectl exec -n gitlab deployment/gitlab-toolbox -- gitlab-rails runner -e production '\
          user = User.new(username: "doug", name: "Doug Unicorn", email: "doug@uds.dev", password: "0123456789!", password_confirmation: "0123456789!"); \
          user.assign_personal_namespace(Organizations::Organization.default_organization); \
          user.skip_confirmation!; \
          user.admin = true; \
          user.save!; \
          puts user.username; puts user.id'

  - name: root-password
    actions:
      - description: Get the root password for GitLab (useful for local dev)
        cmd: ./uds zarf tools kubectl get secret -n gitlab gitlab-gitlab-initial-root-password -o jsonpath={.data.password} | base64 -d
