{{ if .Values.sso -}}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-sso-provider-json
type: Opaque
stringData:
  providers: |
    {
      "name": "openid_connect",
      "label": "SSO",
      "args": {
        "name": "openid_connect",
        "scope": [
          "openid",
          "profile"
        ],
        "response_type": "code",
        "issuer": "https://sso.{{ .Values.domain }}/realms/uds",
        "client_auth_method": "query",
        "discovery": true,
        "uid_field": "preferred_username",
        "client_options": {
          "identifier": "{{ (lookup "v1" "Secret" "gitlab" "sso-client-uds-core-gitlab").data.clientId | b64dec }}",
          "secret": "{{ (lookup "v1" "Secret" "gitlab" "sso-client-uds-core-gitlab").data.secret | b64dec }}",
          "redirect_uri": {{ trimAll "]" (trimAll "[" ((lookup "v1" "Secret" "gitlab" "sso-client-uds-core-gitlab").data.redirectUris | b64dec)) }},
          "end_session_endpoint": "https://sso.{{ .Values.domain }}/realms/uds/protocol/openid-connect/logout"
        }
      }
    }
{{- end }}
